CREATE TABLE IF NOT EXISTS buildings (
  inactive BOOL,
  activity_code CHAR(4),
  address VARCHAR(70),
  city VARCHAR(25),
  state CHAR(2),
  zipcode CHAR(6),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  building_name VARCHAR(100),
  engineer_zone INT,
  ownership VARCHAR(15),
  facility_type VARCHAR(110),
  occupied_status VARCHAR(15),
  square_footage INT,
  year_built INT,
  landmark VARCHAR(3),
  ward SMALLINT,
  first VARCHAR(100),
  last VARCHAR(100),
  acquisition_date DATE,
  lease_expiration_date DATE,
  lease_terms VARCHAR(20),
  operating_hours VARCHAR(50),
  occupancy INT,
  employees INT,
  computers INT,
  levels_above_grade INT,
  levels_below_grade INT,
  retrofit_2015 BOOLEAN,
  retrocommision CHAR(4),
  energy_assessment CHAR(4),
  leed_certification VARCHAR(20),
  leed_points INT,
  energy_star_score_baseline INT,
  energy_star_score_2016 INT,
  eui_baseline INT,
  eui_2016 INT,
  energy_star_comments VARCHAR(125),
  roof_type VARCHAR(50),
  debris enum('Yes','No'),
  drainage enum('Yes','No'),
  physical_damage enum('Yes','No'),
  cracks enum('Yes','No'),
  roof_condition_comments VARCHAR(400),
  hvac_equipment enum('Yes','No'),
  exhaust_fans_working enum('Yes','No'),
  holes_around_equipment enum('Yes','No'),
  open_seams enum('Yes','No'),
  roof_comments VARCHAR(400),
  aec_client VARCHAR(30),
  roof_system VARCHAR(200),
  roof_square_footage INT,
  green_candidate enum('Yes','No'),
  report_comments VARCHAR(400),
  gr_sq_ft_main_roof INT,
  gr_percent_roof_sq_ft_main_roof FLOAT,
  gr_sq_ft_location2 CHAR(4),
  oemc_critical_facility_tier VARCHAR(100),
  nrel_bca_leed_analysis CHAR(4),
  nrel_renewable_reopt_analysis CHAR(4),
  PRIMARY KEY (activity_code)
);

-- load data local infile './data/facilities/buildings_geocoded.csv' into table facilities fields terminated by '`' enclosed by '`' ignore 1 lines;
